[project]
name = "msal_way"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "gokul-converse", email = "gokul@conversedatasolutions.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "msal>=1.39.0",
    "msal-extensions>=1.3.1",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.53.0",
]

[project.scripts]
graph-api = "graph_api:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
